# Generated by Django 2.0.3 on 2018-03-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_value', models.FloatField(default=0)),
                ('buy_volume', models.FloatField(default=0)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_value', models.FloatField(default=0)),
                ('sell_volume', models.FloatField(default=0)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sell',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raise_2.Shares'),
        ),
        migrations.AddField(
            model_name='main',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raise_2.Shares'),
        ),
        migrations.AddField(
            model_name='buy',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raise_2.Shares'),
        ),
    ]
