# Generated by Django 2.0.3 on 2018-05-30 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raise_2', '0004_auto_20180529_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='aktie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='raise_2.Shares'),
            preserve_default=False,
        ),
    ]
