# Generated by Django 2.0.3 on 2018-05-30 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raise_2', '0007_buy_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='share',
            new_name='aktie',
        ),
        migrations.AddField(
            model_name='holders',
            name='anzahl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='holders',
            name='wert',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holders',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
