# Generated by Django 2.0.3 on 2018-06-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_2', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Balance',
            field=models.FloatField(default=0),
        ),
    ]
