# Generated by Django 2.0.3 on 2018-06-05 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raise_2', '0011_profile_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holders',
            old_name='wert',
            new_name='wert_aktuell',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Balance',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='holders',
            name='wert_schnitt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
