# Generated by Django 2.0.3 on 2018-06-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_2', '0012_auto_20180605_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='holders',
            name='gewinn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='holders',
            name='prozent',
            field=models.FloatField(default=0),
        ),
    ]
