# Generated by Django 2.0.3 on 2018-06-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_2', '0013_auto_20180605_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shares',
            name='plus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shares',
            name='prozent',
            field=models.FloatField(default=0),
        ),
    ]
