# Generated by Django 2.0.3 on 2018-06-10 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raise_2', '0015_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wert', models.IntegerField(default=0)),
                ('gewinn', models.FloatField(default=0)),
                ('monat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raise_2.Shares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
