# Generated by Django 2.0.3 on 2018-06-11 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raise_2', '0017_auto_20180610_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
