# Generated by Django 2.0.3 on 2018-06-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raise_2', '0018_auto_20180611_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='sell_value',
            new_name='buy_value',
        ),
        migrations.RenameField(
            model_name='sell',
            old_name='sell_volume',
            new_name='buy_volume',
        ),
    ]
