# Generated by Django 2.0.3 on 2018-06-11 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raise_2', '0019_auto_20180611_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.FloatField(default=0)),
                ('wert_aktuell', models.FloatField(default=0)),
                ('wert_schnitt', models.FloatField(default=0)),
                ('gewinn', models.FloatField(default=0)),
                ('prozent', models.FloatField(default=0)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raise_2.Shares')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
