# Generated by Django 2.0.3 on 2018-06-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raise_2', '0020_raise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raise',
            name='user',
        ),
    ]
