# Generated by Django 2.0.3 on 2018-06-12 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raise_2', '0021_remove_raise_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoriten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raise_2.Shares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
