# Generated by Django 2.0.3 on 2018-06-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_2', '0022_favoriten'),
    ]

    operations = [
        migrations.AddField(
            model_name='raise',
            name='gebuehren',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='raise',
            name='kursgewinn',
            field=models.FloatField(default=0),
        ),
    ]
