# Generated by Django 2.0.3 on 2018-06-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_2', '0023_auto_20180619_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='gebuehren',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sell',
            name='gebuehren',
            field=models.FloatField(default=0),
        ),
    ]
